# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dagger Wrath Games
email: dwrathgames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site designed and maintained by Dagarath to showcase anything and everythings
  related to Dagarath, Dagger Wrath Games or Dagger Wrath Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dagarath.com" # the base hostname & protocol for your site
twitter_username: Dagarath
github_username:  Dagarath

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems: [jekyll-coffeescript,jekyll-paginate]
